### ISSUE TITLE
Cannot find module '../connection.js'

### ISSUE THREAD

**Issue by avermeulen** [avermeulen/hunce-app#5]
@emanuel281 I am getting an error when trying to run the application on my machine.

Please take a look and fix it.

```
Error: Cannot find module '../connection.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/andre/Dropbox/projects/hunce-app/routes/hunches.js:1:80)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by emanuel281** [comment]
var mysql = require("mysql");

module.exports = mysql.createConnection({
    user : "hunchAdmin",
    password : "Coder_Hunch123",
    database : "hunchDB",
    host : "localhost",
    port: 3306
});

That needs to be in the connection.js file

**Comment by avermeulen** [comment]
there's no `connection.js` file in git :(

**Comment by emanuel281** [comment]
You have to create it in the root folder.
I git ignored.

Sorry 😌 

Sent from my Windows Phone 

-----Original Message-----

**Comment by avermeulen** [comment]
why did you do that?

**Comment by avermeulen** [comment]
You should use environment variables if you don't want to put db usernames
etc in the source code.

**Comment by emanuel281** [comment]
It was before I decided to have that sql script.

Sent from my Windows Phone 

-----Original Message-----

**Comment by emanuel281** [comment]
Yeah I'll implement that next week

Sent from my Windows Phone 

-----Original Message-----
